// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketProcessingRestApi.Repository;

namespace TicketProcessingRestApi.Repository.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    partial class TicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TicketProcessingRestApi.Entities.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("assignDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("assignManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("assignPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isResolved")
                        .HasColumnType("bit");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            Attachment = "query.pdf",
                            CreateDate = new DateTime(2021, 11, 10, 12, 51, 4, 626, DateTimeKind.Local).AddTicks(37),
                            Discription = "new query",
                            Priority = "High",
                            TicketType = "IT",
                            assignDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            assignManager = "neha.haridas@gmail.com",
                            assignPerson = "vinay@xyz.com",
                            createdBy = "Anshul@gmail.com",
                            isResolved = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
