version: '3'

services:
  elsadb:
    image: mongo
  smtp4dev:
    image: rnwood/smtp4dev:v3
  elsa.server:
    image: ${DOCKER_REGISTRY-}elsaserver
    build:
      context: .
      dockerfile: Dockerfile
  orderitems.api:
    image: ${DOCKER_REGISTRY-}orderitemsapi
    build:
      context: .
      dockerfile: src/Api/OrderItems/OrderItems.API/Dockerfile
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379 

volumes:
  mongo_data: 
  smtp4dev-data:
