version: '3'

services:
  elsadb:
    image: mongo
  smtp4dev:
    image: rnwood/smtp4dev:v3
  elsa.server:
    image: ${DOCKER_REGISTRY-}elsaserver
    build:
      context: .
      dockerfile: src/Server/Elsa.Server/Dockerfile
  orderitems.api:
    image: ${DOCKER_REGISTRY-}orderitemsapi
    build:
      context: .
      dockerfile: src/Api/OrderItems/OrderItems.API/Dockerfile

volumes:
  mongo_data: 
  smtp4dev-data:
