// <auto-generated />
using System;
using ExpenseClaim.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpenseClaim.Repositories.Migrations
{
    [DbContext(typeof(ClaimDbContext))]
    [Migration("20211110114208_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExpenseClaim.Entities.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("SanctionedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ClaimId");

                    b.ToTable("ExpenseClaims");
                });

            modelBuilder.Entity("ExpenseClaim.Entities.ClaimType", b =>
                {
                    b.Property<int>("ClaimTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("ClaimTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClaimTypeId");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimType");
                });

            modelBuilder.Entity("ExpenseClaim.Entities.ClaimType", b =>
                {
                    b.HasOne("ExpenseClaim.Entities.Claim", null)
                        .WithMany("ClaimItemList")
                        .HasForeignKey("ClaimId");
                });
#pragma warning restore 612, 618
        }
    }
}
