// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20211109083247_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Entities.UserDetails", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UsersDetail");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            AccountNumber = "721702010010565",
                            DocumentName = "Adhar Card",
                            Email = "vivek@xyz.com",
                            MobileNumber = "7754951743",
                            Name = "Vivek"
                        },
                        new
                        {
                            UserId = new Guid("6313179f-7837-473a-a4d5-a5571b43e6a6"),
                            AccountNumber = "721702010010566",
                            DocumentName = "Adhar Card",
                            Email = "amisha@xyz.com",
                            MobileNumber = "7754951745",
                            Name = "Amisha"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
